# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/lisa/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),lisa)

$(call add-radio-file-sha1-checked,radio/abl.img,b52407268dcf7cae0c8b577fd96ff8796c933807)
$(call add-radio-file-sha1-checked,radio/aop.img,a968c79389f1c0260e019ee9bd59a13cdbb972ac)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,7f73fceb7eb262b9fc4347c669473cd647d75d68)
$(call add-radio-file-sha1-checked,radio/cpucp.img,8a72786e252620260a7d5623561ed10af4d1cfc8)
$(call add-radio-file-sha1-checked,radio/devcfg.img,777ea976b5cbea296292f2e9d4a00c0060dd0abe)
$(call add-radio-file-sha1-checked,radio/dsp.img,c21e6e8bf124b76385a8f00c14baf084e9623352)
$(call add-radio-file-sha1-checked,radio/featenabler.img,9b3ab0fcc25b2850c8dee3edf3855ffa135b4148)
$(call add-radio-file-sha1-checked,radio/hyp.img,c399416d1364f809231ea4b0c3b5cba3f12a88dd)
$(call add-radio-file-sha1-checked,radio/imagefv.img,0ff6612e0bac4626eefe2523a4a9871a8b4c3152)
$(call add-radio-file-sha1-checked,radio/keymaster.img,d0ae168d9d655640005d12a61c7ed63c6e502903)
$(call add-radio-file-sha1-checked,radio/modem.img,63a65f89d4bcea92553fa418f56e831f856cc45b)
$(call add-radio-file-sha1-checked,radio/qupfw.img,e2988446e7f8342ae5cd26792269cb2cd708372b)
$(call add-radio-file-sha1-checked,radio/shrm.img,59ccadfc74edb152086d4ecb1013e8b88dd4dbaa)
$(call add-radio-file-sha1-checked,radio/tz.img,9cf452342304707a234eb76d42ed1347b7b755e8)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,6c453b266fa0f689b7c52cfc8d1b47a2f12578b5)
$(call add-radio-file-sha1-checked,radio/xbl.img,f93843df6eff095ed65fcb655ab845dcc35b0699)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,cd39dfd5c32ee42bb604fc8f5de21dbe9fc78101)

endif
